-- Fix delete_products_bulk function to avoid aggregates in RETURNING and improve permission checks
-- Generated by Cascade on 2025-11-09

CREATE OR REPLACE FUNCTION public.delete_products_bulk(
  target_tenant_id uuid,
  target_shop_id uuid,
  delete_all_shops boolean
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  acting_role text;
  acting_tenant uuid;
  deleted_count integer := 0;
BEGIN
  IF target_tenant_id IS NULL THEN
    RAISE EXCEPTION 'target_tenant_id is required';
  END IF;

  IF NOT delete_all_shops AND target_shop_id IS NULL THEN
    RAISE EXCEPTION 'target_shop_id is required when delete_all_shops is false';
  END IF;

  -- Récupérer le rôle et le tenant de l'utilisateur courant
  acting_role := public.get_user_role();
  acting_tenant := public.get_user_tenant_id();

  IF acting_role IS NULL THEN
    RAISE EXCEPTION 'Permission denied: unable to determine user role';
  END IF;

  -- Seuls super_admin et rôles owner/admin/manager du tenant ciblé peuvent supprimer en lot
  IF NOT public.is_super_admin() THEN
    IF acting_tenant IS NULL OR acting_tenant <> target_tenant_id THEN
      RAISE EXCEPTION 'Permission denied for tenant %', target_tenant_id;
    END IF;

    IF acting_role NOT IN ('owner', 'admin', 'manager') THEN
      RAISE EXCEPTION 'Permission denied: role % cannot delete products in bulk', acting_role;
    END IF;
  END IF;

  -- Préparer les produits ciblés
  WITH target_products AS (
    SELECT id
    FROM public.products
    WHERE tenant_id = target_tenant_id
      AND (delete_all_shops OR shop_id = target_shop_id)
  ),
  deleted_sale_items AS (
    DELETE FROM public.sale_items si
    WHERE si.product_id IN (SELECT id FROM target_products)
    RETURNING si.product_id
  ),
  deleted_inventory AS (
    DELETE FROM public.inventory inv
    WHERE inv.product_id IN (SELECT id FROM target_products)
      AND (delete_all_shops OR inv.shop_id = target_shop_id)
    RETURNING inv.product_id
  ),
  deleted_products AS (
    DELETE FROM public.products p
    WHERE p.id IN (SELECT id FROM target_products)
    RETURNING p.id
  )
  SELECT COUNT(*) INTO deleted_count FROM deleted_products;

  RETURN COALESCE(deleted_count, 0);
END;
$$;

COMMENT ON FUNCTION public.delete_products_bulk(uuid, uuid, boolean)
IS 'Delete products (and related inventory/sale items) either for a whole tenant or a specific shop. Returns number of deleted products.';
